### ISSUE TITLE
Issue Building `Facebook-SDK-Swift at "0.2.0"` w/ Carthage

### ISSUE THREAD

**Issue by csauvage** [facebook/facebook-sdk-swift#142]
Since a couple of days, I'm facing and issue while building Fb Swift SDK with Carthage. 

Here is the extract of my cartfile
```bash
#RX
github "facebook/Facebook-SDK-Swift" ~> 0.2.0
```

And this is Carthage build output 

```bash

*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace "/Users/csauvage/Github/XXXXX/XXXXXXX/Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace" -scheme FBSDKCoreKit-Dynamic -configuration Release -derivedDataPath /Users/csauvage/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.20.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/1j/l9l79_690zq36chnt1rh8qp40000gn/T/carthage-xcodebuild.KaEpeu.log
```

Has someone experienced this issue before ?

**Comment by meekay** [comment]
The issue is that a the Facebook iOS SDK no longer compiles using Xcode 8.3, which was just released a few days ago. Somebody submitted a pull request for a fix but none of the Facebook developers seem to be responding.

https://github.com/facebook/facebook-ios-sdk/pull/853

**Comment by AndrewSB** [comment]
As a temp workaround, I'm using

```
github "AndrewSB/facebook-sdk-swift" "master"
```

which depends on @adomanico's fork of the Facebook sdk

**Comment by chooblarin** [comment]
@AndrewSB 

It's not still working with my environment.

```
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/chooblarin/Library/Developer/Xcode/DerivedData/FacebookSwift-cohydgngcvlnmveefpzxfbsyokvb/Build/Intermediates/FBSDKCoreKit.build/Release-iphoneos/FBSDKCoreKit-Dynamic.build/Objects-normal/armv7/FBSDKGraphRequestPiggybackManager.o FBSDKCoreKit/Internal/Network/FBSDKGraphRequestPiggybackManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
/Users/chooblarin/Xcode/sample/Carthage/Checkouts/facebook-sdk-swift/Carthage/Checkouts/facebook-ios-sdk/FBSDKCoreKit/FBSDKCoreKit/module.modulemap:1:18: error: redefinition of module 'FBSDKCoreKit'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/chooblarin/Xcode/sample/Carthage/Checkouts/facebook-sdk-swift/FacebookSwift.xcworkspace -scheme FacebookShare -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/chooblarin/Library/Developer/Xcode/DerivedData/FacebookSwift-cohydgngcvlnmveefpzxfbsyokvb/Build/Intermediates/FBSDKCoreKit.build/Release-iphoneos/FBSDKCoreKit-Dynamic.build/Objects-normal/armv7/FBSDKGraphRequestPiggybackManager.o FBSDKCoreKit/Internal/Network/FBSDKGraphRequestPiggybackManager.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by mcfedr** [comment]
Is there any advantage to using this over the normal facebook-ios-sdk?

**Comment by AndrewSB** [comment]
@chooblarin: yeah, I noticed the same thing later. It looks like my branch doesnt completely fix the issue, it now looks as if theres something wrong with the `.modulemaps`

@mcfedr: just more swifty, no new functionality. The additions are all mentioned in facebook-ios-sdk's README

**Comment by Alak** [comment]
Any news ?

**Comment by Alak** [comment]
@nlutsenko

**Comment by nlutsenko** [comment]
@alak, any chance you can try master?
The changes are in, need to test it and cut the release and if you can help me test and confirm that it works - it would be tremendous help.

**Comment by Alak** [comment]
@nlutsenko ok I'll test :)

**Comment by QuynhNguyen** [comment]
@nlutsenko Built fine. Cut the release and ship it :)

**Comment by AndrewSB** [comment]
Worked for me too, FYI

**Comment by ygbr** [comment]
me too!
can we have a 0.3.0 soon? There are other cool and necessary changes on master that would be nice to have such as AppEvents userId and fixes for the loginManager sdkbehavior. Anyway, a lot has changed since 0.2.0 released in September 2016.

**Comment by jorgelub12** [comment]
Hello, I have the same problem, how can I fix this?

**Comment by AndrewSB** [comment]
@jorgelub12: you can just point to master, and it should work 😊

**Comment by sjmueller** [comment]
@AndrewSB I tried your master but there are still errors. Cartfile:
```
github "AndrewSB/facebook-sdk-swift" "master"
```
During `carthage update --platform ios`
```
*** Fetching facebook-sdk-swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.8.4"
*** Checking out facebook-ios-sdk at "830cc8eff7c3d4615bd4d6a8cad238bf9f17bdb5"
*** Checking out facebook-sdk-swift at "9faec85536447205fa696cbcbb5515f916966320"
*** xcodebuild output can be found in /var/folders/3h/vl98yg6n2t1f4lhpnmww978w0000gn/T/carthage-xcodebuild.DbOTjF.log
*** Building scheme "Bolts-iOS-Dynamic" in Bolts.xcodeproj
*** Building scheme "FBSDKCoreKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKLoginKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FBSDKShareKit-Dynamic" in FacebookSDK.xcworkspace
*** Building scheme "FacebookLogin" in FacebookSwift.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Carthage/Checkouts/facebook-sdk-swift/FacebookSwift.xcworkspace -scheme FacebookLogin -configuration Release -derivedDataPath /Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-sdk-swift/9faec85536447205fa696cbcbb5515f916966320 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

Inside of log
```
The following build commands failed:
CompileC /Library/Caches/org.carthage.CarthageKit/DerivedData/Facebook-SDK-Swift/9faec85536447205fa696cbcbb5515f916966320/Build/Intermediates/FBSDKCoreKit.build/Release-iphoneos/FBSDKCoreKit-Dynamic.build/Objects-normal/armv7/FBSDKGraphRequest.o FBSDKCoreKit/FBSDKGraphRequest.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by AndrewSB** [comment]
Oh sorry! Not my master, facebook-sdk-swift's master

**Comment by jorgelub12** [comment]
Didn't work either.

Cartfile:
github "facebook/Facebook-SDK-Swift" "master"

Build Failed
Task failed with exit code 65:
/usr/bin/xcrun xcodebuild -workspace /Users/sg/ks/Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKShareKit_TV-Dynamic -configuration Release -derivedDataPath /Users/sg-produccione/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.21.0 -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/r9/vqk9d0ts7f9d9hvxkw6nhr_m0000gn/T/carthage-xcodebuild.wYG3tU.log

**Comment by AndrewSB** [comment]
can you delete your derived data and try again? It would also be helpful to see what's in your xcodebuild log to see what went wrong (`/var/folders/r9/vqk9d0ts7f9d9hvxkw6nhr_m0000gn/T/carthage-xcodebuild.wYG3tU.log`). Could you share that in a pastebin or gist?

**Comment by proactive-solutions** [comment]
I am facing the same issue with Xcode 8.3.1

**Comment by mhillebrand** [comment]
```** BUILD FAILED **


The following build commands failed:
	Ld /Users/mhillebrand/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.22.0/Build/Intermediates/FBSDKPlacesKit.build/Release-iphonesimulator/FBSDKPlacesKit-Dynamic.build/Objects-normal/i386/FBSDKPlacesKit normal i386
	Ld /Users/mhillebrand/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.22.0/Build/Intermediates/FBSDKPlacesKit.build/Release-iphonesimulator/FBSDKPlacesKit-Dynamic.build/Objects-normal/x86_64/FBSDKPlacesKit normal x86_64
(2 failures)```

**Comment by jorgelub12** [comment]
@AndrewSB I tried deleting the derived data and still happening.

**Comment by asciifaceman** [comment]
```
Undefined symbols for architecture arm64:
  "_CBAdvertisementDataManufacturerDataKey", referenced from:
      -[FBSDKPlacesBluetoothScanner centralManager:didDiscoverPeripheral:advertisementData:RSSI:] in FBSDKPlacesBluetoothScanner.o
  "_CBAdvertisementDataServiceDataKey", referenced from:
      -[FBSDKPlacesBluetoothScanner centralManager:didDiscoverPeripheral:advertisementData:RSSI:] in FBSDKPlacesBluetoothScanner.o
  "_CBCentralManagerScanOptionAllowDuplicatesKey", referenced from:
      -[FBSDKPlacesBluetoothScanner _startScan] in FBSDKPlacesBluetoothScanner.o
  "_CNCopyCurrentNetworkInfo", referenced from:
      -[FBSDKPlacesManager _networkInfo] in FBSDKPlacesManager.o
  "_CNCopySupportedInterfaces", referenced from:
      -[FBSDKPlacesManager _networkInfo] in FBSDKPlacesManager.o
  "_OBJC_CLASS_$_CBCentralManager", referenced from:
      objc-class-ref in FBSDKPlacesBluetoothScanner.o
  "_OBJC_CLASS_$_CBUUID", referenced from:
      objc-class-ref in FBSDKPlacesBluetoothScanner.o
  "_OBJC_CLASS_$_CLLocationManager", referenced from:
      objc-class-ref in FBSDKPlacesManager.o
ld: symbol(s) not found for architecture arm64

** BUILD FAILED **
```

the problem is with the upstream sdk I think

**Comment by sjmueller** [comment]
I would recommend locking up your `Cartfile` like this for now:
```
github "facebook/facebook-sdk-swift" "master"
github "facebook/facebook-ios-sdk" "sdk-version-4.21.0"
```
Just verfied from a fresh install (delete Cartfile.resolved + Carthage folder) that this combo works.

**Comment by jorgelub12** [comment]
Still not working.

Cartfile:
github "facebook/Facebook-SDK-Swift" "master"
github "facebook/Facebook-ios-sdk" "sdk-version-4.21.0"

Logs:
org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.21.0/Build/Intermediates/FBSDKShareKit.build/Release-appletvos/FBSDKShareKit_TV-Dynamic.build/Objects-normal/arm64/FBSDKShareKit_dependency_info.dat -o /Users/sg-produccione/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.21.0/Build/Products/Release-appletvos/FBSDKShareKit.framework/FBSDKShareKit
Undefined symbols for architecture arm64:
"_CGContextFillEllipseInRect", referenced from:
+[FBSDKShareUtility imageWithCircleColor:canvasSize:circleSize:] in FBSDKShareUtility.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **
The following build commands failed:
Ld /Users/sg-produccione/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.21.0/Build/Products/Release-appletvos/FBSDKShareKit.framework/FBSDKShareKit normal arm64
(1 failure)

**Comment by mhillebrand** [comment]
Now that I've upgraded to Xcode 8.3.2, the Cartfile provided by @sjmueller does indeed appear to work.

`github "facebook/facebook-sdk-swift" "master"
github "facebook/facebook-ios-sdk" "sdk-version-4.21.0"`

...and this worked before and after updating Carthage to 0.21.0.

**Comment by mayoralito** [comment]
I'm using Xcode 8.3.1 and this is what I followed:

1. Deleted derived data.
2. Removed Carthage folder: `rm -r ./Carthage`
3. Updated `Cartfile` with:
```
github "facebook/facebook-sdk-swift" "master"
github "facebook/facebook-ios-sdk" "sdk-version-4.21.0"
```
4. Run Carthage command: `carthage update --platform iOS --no-use-binaries`

Output:
```
*** Fetching facebook-sdk-swift
*** Fetching facebook-ios-sdk
*** Fetching Bolts-ObjC
*** Checking out Bolts-ObjC at "1.8.4"
*** Checking out facebook-ios-sdk at "sdk-version-4.21.0"
```

**And it worked!**

**Comment by meekay** [comment]
Update. This one works.

`
github "facebook/Facebook-SDK-Swift" "master"
github "facebook/facebook-ios-sdk" == 4.21
`

This one fails.

`
github "facebook/Facebook-SDK-Swift" "master"
github "facebook/facebook-ios-sdk" == 4.22
`

Cleaned derived data, etc. I'm not reassured.

**Comment by hientrq** [comment]
@mayoralito This works for me

**Comment by bitkill** [comment]
Same error here, with latest release, 0.2.0. When can we get this fixed?

**Comment by Appendit** [comment]
It's really annoying. Can we get a fix pls?

**Comment by hixfield** [comment]
Facebook, any fix comming for this?

**Comment by Appendit** [comment]
Got it working. Using target ios only on compiling.

But i'm wondering how you you use GraphResponse as a Dictionary

**Comment by hixfield** [comment]
how do you specify "Using target ios only on compiling" in Carthage?

**Comment by mylifeasdog** [comment]
`carthage bootstrap --platform iOS`

**Comment by txaiwieser** [comment]
Please, give us an update for this repo, its meeting really anoying using fb-sdk with Swift and Carthage
